// GENERATED BROWSER MIRROR — source of truth: src/system-status.ts
// Keep this file synchronized with the canonical TypeScript registry.
export const DNS_SYSTEM_STATUS_VERSION = '0.2.0';
export const DNS_SYSTEM_STATUS_VERIFIED_AT = '2026-10-01';

export const DNS_SYSTEM_STATUS_CRITERIA = [
  { id: 'designSystem', label: 'Design System' },
  { id: 'sharedData', label: 'Shared Data' },
  { id: 'firebase', label: 'Firebase' },
  { id: 'auth', label: 'Auth' },
  { id: 'sharedAssets', label: 'Shared Assets' },
  { id: 'regionLogos', label: 'Region Logos' },
  { id: 'motion', label: 'Motion' },
  { id: 'dataContracts', label: 'Data Contracts' },
  { id: 'accessibility', label: 'Accessibility' },
];

export const DNS_SYSTEM_STATUS = [
  {
    id: 'shared-data',
    label: 'DNS Shared Data',
    repo: 'dolomitinordicski/dns-shared-data',
    phase: 'foundation-source',
    firebaseProject: 'dns-core',
    datasetVersion: 'Canonical v1.6 · Operational schema 4 · Design System v1.12.1',
    criteria: {
      designSystem: 'adopted',
      sharedData: 'adopted',
      firebase: 'adopted',
      auth: 'na',
      sharedAssets: 'adopted',
      regionLogos: 'adopted',
      motion: 'adopted',
      dataContracts: 'adopted',
      accessibility: 'adopted',
    },
    note: 'Canonical source for shared contracts, assets, design tokens and Firebase rules/seeds.',
  },
  {
    id: 'data-entry',
    label: 'DNS Data Entry',
    repo: 'dolomitinordicski/DNS-Data-Entry',
    phase: 'foundation-aligned',
    firebaseProject: 'dns-core',
    datasetVersion: 'Shared package pinned to Foundation / Design System v1.12.1',
    criteria: {
      designSystem: 'adopted',
      sharedData: 'adopted',
      firebase: 'adopted',
      auth: 'adopted',
      sharedAssets: 'adopted',
      regionLogos: 'adopted',
      motion: 'adopted',
      dataContracts: 'adopted',
      accessibility: 'adopted',
    },
    note: 'Reference operational consumer. Shared navigation runtime v1.12.1, stable first paint, regional assets, module-level Data Contracts and Accessibility v1 are adopted.',
  },
  {
    id: 'polls',
    label: 'DNS Polls',
    repo: 'dolomitinordicski/DNS-Polls-tool',
    phase: 'foundation-aligned',
    firebaseProject: 'separate Polls / PII domain',
    datasetVersion: 'Shared package pinned to Foundation / Design System v1.12.1',
    criteria: {
      designSystem: 'adopted',
      sharedData: 'partial',
      firebase: 'adopted',
      auth: 'adopted',
      sharedAssets: 'notYet',
      regionLogos: 'na',
      motion: 'adopted',
      dataContracts: 'na',
      accessibility: 'adopted',
    },
    note: 'Foundation shell v1.12.1 is adopted with shared navigation, motion, interaction and Accessibility v1. Privacy-sensitive poll data remains intentionally isolated in the separate Polls / PII domain; brand assets are still local copies.',
  },
  {
    id: 'flyer-studio',
    label: 'DNS Flyer Studio',
    repo: 'dolomitinordicski/DNS-Flyer-Studio',
    phase: 'in-migration',
    firebaseProject: 'app-specific Firebase configuration',
    datasetVersion: 'No shared package pin detected',
    criteria: {
      designSystem: 'notYet',
      sharedData: 'notYet',
      firebase: 'partial',
      auth: 'pending',
      sharedAssets: 'notYet',
      regionLogos: 'partial',
      motion: 'notYet',
      dataContracts: 'notYet',
      accessibility: 'notYet',
    },
    note: 'Regional and DNS logos are currently stored locally; migration should replace local copies with shared manifest resolution.',
  },
  {
    id: 'fair',
    label: 'DNS FAIR',
    repo: 'dolomitinordicski/fairmodel',
    phase: 'foundation-ui-aligned',
    firebaseProject: 'fair-modell · separate operational persistence',
    datasetVersion: 'Foundation / Design System v1.13.0 · FAIR contract foundation-defined',
    criteria: {
      designSystem: 'adopted',
      sharedData: 'adopted',
      firebase: 'partial',
      auth: 'pending',
      sharedAssets: 'adopted',
      regionLogos: 'adopted',
      motion: 'adopted',
      dataContracts: 'partial',
      accessibility: 'adopted',
    },
    note: 'Foundation shell, canonical navigation, shared print runtime/tokens, shared web logo, canonical regional-logo manifest, motion/interaction and Accessibility v1 are adopted. FAIR uses Tailwind v4/Vite with legacy popup printing, local logo copies, Tailwind v3/PostCSS config and the vanilla-JS backup removed. FAIR calculation logic and existing fair-modell persistence remain unchanged; the FAIR Data Contract is still foundation-defined pending data-domain integration.',
  },
  {
    id: 'analytics',
    label: 'DNS Analytics',
    repo: null,
    phase: 'pending-audit',
    firebaseProject: 'DNS Platform target',
    datasetVersion: 'Foundation ownership defined; measurement contract pending integration',
    criteria: {
      designSystem: 'pending',
      sharedData: 'pending',
      firebase: 'pending',
      auth: 'pending',
      sharedAssets: 'pending',
      regionLogos: 'pending',
      motion: 'pending',
      dataContracts: 'partial',
      accessibility: 'pending',
    },
    note: 'Analytics ownership and scope model are defined; production and extended implementations still require non-destructive integration audit.',
  },
  {
    id: 'faktura',
    label: 'DNS Faktura / Commercial',
    repo: null,
    phase: 'planned',
    firebaseProject: 'DNS Commercial target',
    datasetVersion: 'Foundation boundary defined',
    criteria: {
      designSystem: 'notYet',
      sharedData: 'notYet',
      firebase: 'notYet',
      auth: 'notYet',
      sharedAssets: 'notYet',
      regionLogos: 'na',
      motion: 'notYet',
      dataContracts: 'partial',
      accessibility: 'notYet',
    },
    note: 'Commercial/billing-preparation domain is planned; XGLA4 remains the accounting authority.',
  },
  {
    id: 'partner-portal',
    label: 'Partner Portal',
    repo: null,
    phase: 'planned',
    firebaseProject: 'DNS Platform target',
    datasetVersion: 'Foundation access model defined',
    criteria: {
      designSystem: 'notYet',
      sharedData: 'notYet',
      firebase: 'notYet',
      auth: 'partial',
      sharedAssets: 'notYet',
      regionLogos: 'partial',
      motion: 'notYet',
      dataContracts: 'partial',
      accessibility: 'pending',
    },
    note: 'Portal role, memberships and access-grant model are defined at Foundation level; application adoption remains pending.',
  },
];
