// GENERATED BROWSER MIRROR — source of truth: src/system-status.ts
// Keep this file synchronized with the canonical TypeScript registry.
export const DNS_SYSTEM_STATUS_VERSION = '0.1.0';
export const DNS_SYSTEM_STATUS_VERIFIED_AT = '2026-10-01';

export const DNS_SYSTEM_STATUS_CRITERIA = [
  { id: 'designSystem', label: 'Design System' },
  { id: 'sharedData', label: 'Shared Data' },
  { id: 'firebase', label: 'Firebase' },
  { id: 'auth', label: 'Auth' },
  { id: 'sharedAssets', label: 'Shared Assets' },
  { id: 'regionLogos', label: 'Region Logos' },
  { id: 'motion', label: 'Motion' },
  { id: 'dataContracts', label: 'Data Contracts' },
];

export const DNS_SYSTEM_STATUS = [
  {
    id: 'shared-data',
    label: 'DNS Shared Data',
    repo: 'dolomitinordicski/dns-shared-data',
    phase: 'foundation-source',
    firebaseProject: 'dns-core',
    datasetVersion: 'Canonical v1.6 · Operational schema 4 · Design System v1.9',
    criteria: {
      designSystem: 'adopted',
      sharedData: 'adopted',
      firebase: 'adopted',
      auth: 'na',
      sharedAssets: 'adopted',
      regionLogos: 'adopted',
      motion: 'adopted',
      dataContracts: 'adopted',
    },
    note: 'Canonical source for shared contracts, assets, design tokens and Firebase rules/seeds.',
  },
  {
    id: 'data-entry',
    label: 'DNS Data Entry',
    repo: 'dolomitinordicski/DNS-Data-Entry',
    phase: 'foundation-aligned',
    firebaseProject: 'dns-core',
    datasetVersion: 'Shared package pinned through Design System v1.9',
    criteria: {
      designSystem: 'adopted',
      sharedData: 'adopted',
      firebase: 'adopted',
      auth: 'adopted',
      sharedAssets: 'adopted',
      regionLogos: 'adopted',
      motion: 'adopted',
      dataContracts: 'notYet',
    },
    note: 'Reference operational consumer. Data Contracts export was added after its current shared-package pin.',
  },
  {
    id: 'polls',
    label: 'DNS Polls',
    repo: 'dolomitinordicski/DNS-Polls-tool',
    phase: 'in-migration',
    firebaseProject: 'separate Polls / PII domain',
    datasetVersion: 'Shared package pinned to an earlier foundation snapshot',
    criteria: {
      designSystem: 'partial',
      sharedData: 'partial',
      firebase: 'adopted',
      auth: 'adopted',
      sharedAssets: 'notYet',
      regionLogos: 'na',
      motion: 'adopted',
      dataContracts: 'na',
    },
    note: 'Privacy-sensitive domain remains intentionally separate. Shared motion is adopted; brand assets are still local copies.',
  },
  {
    id: 'flyer-studio',
    label: 'DNS Flyer Studio',
    repo: 'dolomitinordicski/DNS-Flyer-Studio',
    phase: 'in-migration',
    firebaseProject: 'app-specific Firebase configuration',
    datasetVersion: 'No shared package pin detected',
    criteria: {
      designSystem: 'notYet',
      sharedData: 'notYet',
      firebase: 'partial',
      auth: 'pending',
      sharedAssets: 'notYet',
      regionLogos: 'partial',
      motion: 'notYet',
      dataContracts: 'notYet',
    },
    note: 'Regional and DNS logos are currently stored locally; migration should replace local copies with shared manifest resolution.',
  },
  {
    id: 'fair',
    label: 'DNS FAIR',
    repo: null,
    phase: 'pending-audit',
    firebaseProject: 'DNS Platform target',
    datasetVersion: 'Foundation ownership defined; runtime contract pending refactor',
    criteria: {
      designSystem: 'pending',
      sharedData: 'pending',
      firebase: 'pending',
      auth: 'pending',
      sharedAssets: 'pending',
      regionLogos: 'pending',
      motion: 'pending',
      dataContracts: 'partial',
    },
    note: 'FAIR ownership is defined in the Foundation; repository/runtime adoption must be audited during the planned refactor.',
  },
  {
    id: 'analytics',
    label: 'DNS Analytics',
    repo: null,
    phase: 'pending-audit',
    firebaseProject: 'DNS Platform target',
    datasetVersion: 'Foundation ownership defined; measurement contract pending integration',
    criteria: {
      designSystem: 'pending',
      sharedData: 'pending',
      firebase: 'pending',
      auth: 'pending',
      sharedAssets: 'pending',
      regionLogos: 'pending',
      motion: 'pending',
      dataContracts: 'partial',
    },
    note: 'Analytics ownership and scope model are defined; production and extended implementations still require non-destructive integration audit.',
  },
  {
    id: 'faktura',
    label: 'DNS Faktura / Commercial',
    repo: null,
    phase: 'planned',
    firebaseProject: 'DNS Commercial target',
    datasetVersion: 'Foundation boundary defined',
    criteria: {
      designSystem: 'notYet',
      sharedData: 'notYet',
      firebase: 'notYet',
      auth: 'notYet',
      sharedAssets: 'notYet',
      regionLogos: 'na',
      motion: 'notYet',
      dataContracts: 'partial',
    },
    note: 'Commercial/billing-preparation domain is planned; XGLA4 remains the accounting authority.',
  },
  {
    id: 'partner-portal',
    label: 'Partner Portal',
    repo: null,
    phase: 'planned',
    firebaseProject: 'DNS Platform target',
    datasetVersion: 'Foundation access model defined',
    criteria: {
      designSystem: 'notYet',
      sharedData: 'notYet',
      firebase: 'notYet',
      auth: 'partial',
      sharedAssets: 'notYet',
      regionLogos: 'partial',
      motion: 'notYet',
      dataContracts: 'partial',
    },
    note: 'Portal role, memberships and access-grant model are defined at Foundation level; application adoption remains pending.',
  },
];
