export const DNS_DATA_CONTRACTS_VERSION = '0.2.0' as const;

export const DNS_DATA_CONTRACTS = [
  {
    id: 'master-reference',
    label: 'Canonical master data',
    status: 'implemented',
    owner: 'DNS Shared Data / DNS Platform',
    runtime: 'DNS_Core',
    collections: ['reportingAreas', 'destinations', 'organizations', 'organizationRelationships', 'seasons'],
    source: 'src/canonical-data.ts',
    schema: 'Canonical Dataset v1.6 · schema 2',
    write: 'Repository/admin seed only',
    read: 'Public reference read',
    fields: ['id', 'canonicalName', 'localizedName', 'aliases', 'active'],
    relations: ['Reporting Area → Destination', 'Organization ↔ Reporting Area', 'Organization ↔ Destination', 'Season → operational data'],
  },
  {
    id: 'access',
    label: 'Identity & access',
    status: 'implemented',
    owner: 'DNS Platform',
    runtime: 'DNS_Core',
    collections: ['users', 'memberships', 'accessGrants'],
    source: 'src/access-control.ts',
    schema: 'Access Control schema 2',
    write: 'Trusted DNS administration',
    read: 'Authenticated user · own authorization context',
    fields: ['userId', 'organizationId', 'role', 'scopeType', 'scopeId', 'permissions', 'active'],
    relations: ['User → Membership → Organization', 'User → Access Grant → canonical scope'],
  },
  {
    id: 'pricing',
    label: 'Pricing',
    status: 'implemented',
    owner: 'DNS operational pricing',
    runtime: 'DNS_Core',
    collections: ['pricingConfigs'],
    source: 'src/seasonal-operational-data.ts',
    schema: 'Seasonal Operational schema 4',
    write: 'Authorized pricing managers',
    read: 'Authorized operational tools',
    fields: ['seasonId', 'productCode', 'scopeType', 'scopeId', 'salesChannel', 'unitPrice', 'settlementUnitPrice'],
    relations: ['Season → Pricing', 'Scope → Pricing', 'Pricing → Sales snapshot'],
  },
  {
    id: 'order-catalog',
    label: 'Order catalogue & form setup',
    status: 'implemented',
    owner: 'DNS Commercial',
    runtime: 'DNS_Core',
    collections: ['orderCatalogItems', 'orderFormConfigs', 'orderSetupImports', 'pocketfolderSetupImports', 'pocketfolderSourceRows', 'deliveryLocations'],
    source: 'src/seasonal-operational-data.ts',
    schema: 'Seasonal Operational schema 4',
    write: 'DNS admin / controlled import',
    read: 'Authorized order tools',
    fields: ['seasonId', 'category', 'code', 'label', 'displayOrder', 'catalogItemIds', 'organizationIds', 'pocketfolder', 'deliveryLocation', 'Pocketfolder source row'],
    relations: ['Season → Order catalogue', 'Order form → Organizations', 'Order form → Catalogue items', 'Organization → Delivery location', 'Pocketfolder edition → Reporting Area', 'Pocketfolder source rows → immutable source view'],
  },
  {
    id: 'ticket-orders',
    label: 'Physical & ticket orders',
    status: 'implemented',
    owner: 'DNS Commercial',
    runtime: 'DNS_Core',
    collections: ['ticketOrders', 'ticketOrderLines', 'publicOrderShares'],
    source: 'src/seasonal-operational-data.ts',
    schema: 'Seasonal Operational schema 4 · Order persistence v0.4',
    write: 'Authorized contributors / DNS admin',
    read: 'Authorized order scope',
    fields: ['seasonId', 'organizationId', 'reportingAreaId', 'category', 'status', 'catalogItemId', 'quantity', 'pricing'],
    relations: ['Organization → Order', 'Order → Order Lines', 'Order Line → Catalogue Item', 'Pocketfolder → Delivery location', 'Order → Billing preparation'],
  },
  {
    id: 'billing-preparation',
    label: 'Faktura / billing preparation',
    status: 'foundation-defined',
    owner: 'DNS Commercial',
    runtime: 'DNS Commercial / target',
    collections: ['billingRuns', 'billingLines', 'billingAdjustments'],
    source: 'src/billing-preparation.ts',
    schema: 'Billing Preparation v0.1',
    write: 'Authorized DNS billing management',
    read: 'Authorized DNS management',
    fields: ['seasonId', 'organizationId', 'reportingAreaId', 'source.type', 'source.sourceId', 'description', 'quantity', 'unitAmount', 'amount', 'included', 'status'],
    relations: ['FAIR result → Billing line', 'IDM Premium → Billing line', 'Order → Billing line', 'Seasonal extra → Billing line', 'Billing lines → Organization summary'],
  },
  {
    id: 'ticket-sales',
    label: 'Ticket sales',
    status: 'implemented',
    owner: 'DNS operational data / Analytics input',
    runtime: 'DNS_Core',
    collections: ['ticketSales'],
    source: 'src/seasonal-operational-data.ts',
    schema: 'Seasonal Operational schema 4',
    write: 'Authorized sales contributors',
    read: 'Authorized operational / analytical tools',
    fields: ['seasonId', 'organizationId', 'reportingAreaId', 'destinationId', 'productCode', 'quantity', 'pricing', 'calculatedAmount'],
    relations: ['Organization → Sales', 'Reporting Area → Sales', 'Pricing → Sales snapshot', 'Sales → Analytics'],
  },
  {
    id: 'kp',
    label: 'KP / track reporting',
    status: 'implemented',
    owner: 'DNS operational data / Analytics input',
    runtime: 'DNS_Core',
    collections: ['kpMilestones', 'kpEntries', 'kpFairValidations'],
    source: 'src/seasonal-operational-data.ts',
    schema: 'Seasonal Operational schema 4',
    write: 'Authorized KP contributors',
    read: 'Authorized operational / analytical tools',
    fields: ['seasonId', 'entityType', 'entityId', 'reportingAreaId', 'referenceKm', 'milestones.openedKm', 'milestones.artificialSnowKm', 'includeInKp', 'FAIR validation snapshot'],
    relations: ['Organization → KP input', 'Reporting Area → KP aggregation', 'KP FAIR candidate → validation snapshot', 'KP → Analytics / FAIR input after validation'],
  },
  {
    id: 'submissions-revisions',
    label: 'Submission & revision control',
    status: 'implemented',
    owner: 'DNS Platform',
    runtime: 'DNS_Core',
    collections: ['seasonalSubmissions', 'operationalRevisions'],
    source: 'src/seasonal-operational-data.ts',
    schema: 'Seasonal Operational schema 4',
    write: 'Authorized contributors / reviewers',
    read: 'Authorized verification tools',
    fields: ['seasonId', 'organizationId', 'domain', 'status', 'entityType', 'entityId', 'correctionReason', 'correctedAt'],
    relations: ['Operational record → Revision', 'Organization → Submission', 'Submission → verification workflow'],
  },
  {
    id: 'analytics',
    label: 'Analytics measurements',
    status: 'foundation-defined',
    owner: 'Analytics',
    runtime: 'DNS Platform / target',
    collections: [],
    source: 'DNS Foundation v1.2',
    schema: 'Contract to be finalized during Analytics integration',
    write: 'Analytics ingestion / approved operational sources',
    read: 'Analytics · FAIR · management views',
    fields: ['seasonId', 'metricId', 'scopeType', 'scopeId', 'value', 'source'],
    relations: ['Operational facts → Analytics', 'Analytics → FAIR', 'Analytics → Management View'],
  },
  {
    id: 'fair',
    label: 'FAIR model & results',
    status: 'foundation-defined',
    owner: 'FAIR',
    runtime: 'DNS Platform / target',
    collections: [],
    source: 'DNS Foundation v1.2',
    schema: 'Contract to be finalized during FAIR refactor',
    write: 'FAIR calculation / authorized FAIR management',
    read: 'FAIR · Analytics management view',
    fields: ['seasonId', 'scopeId', 'parameters', 'score', 'contribution', 'approvalStatus'],
    relations: ['Analytics facts → FAIR', 'FAIR parameters → FAIR result', 'FAIR result → Analytics/Management View'],
  },
] as const;

export type DNSDataContract = (typeof DNS_DATA_CONTRACTS)[number];
