export const DNS_DESIGN_SYSTEM_VERSION = '1.3.0' as const;

export const DNS_DESIGN_SYSTEM = {
  id: 'v1',
  name: 'DNS Design System',
  version: DNS_DESIGN_SYSTEM_VERSION,
  status: 'active',
  brandSources: {
    colors: 'DNS Partner Portal',
    interaction: 'Dolomiti NordicSki public website',
    dataUi: 'DNS Analytics',
  },
  colors: {
    deep: '#0D4D5E',
    mid: '#417483',
    light: '#AAD0D1',
    background: '#F4F8F9',
    surface: '#FFFFFF',
    darkText: '#313131',
    gray: '#DDDDDD',
    primaryDark: '#08343F',
    secondaryDark: '#7BBABC',
    mutedText: '#5A7F8A',
    positive: '#0F6E56',
    negative: '#993C1D',
    border: 'rgba(65,116,131,.20)',
    subtleBorder: 'rgba(65,116,131,.08)',
  },
  typography: {
    primaryFamily: 'Be Vietnam Pro',
    secondaryFamily: 'Roboto',
    primaryWeights: [300, 400, 500, 600, 700, 800, 900],
    secondaryWeights: [300, 400, 500, 700, 900],
    baseFontSizePx: 13,
    sectionTitlePx: 11,
    labelPx: 10,
    microPx: 9,
    valuePx: 21,
    headingPx: 22,
    uppercaseTrackingEm: 0.06,
  },
  shape: {
    cardRadiusPx: 10,
    controlRadiusPx: 6,
    badgeRadiusPx: 20,
  },
  spacing: {
    pageXRem: 1.8,
    pageYRem: 1.3,
    cardPaddingRem: 1.1,
    cardGapPx: 14,
    compactGapPx: 8,
  },
  shadow: {
    card: '0 1px 4px rgba(13,77,94,.07)',
    header: '0 1px 0 rgba(255,255,255,.08)',
    floatingControl: '0 4px 6px rgba(0,0,0,.10)',
  },
  motion: {
    fastMs: 200,
    standardMs: 300,
    revealMs: 600,
    easing: 'ease',
    hoverScale: 1.05,
    touchScale: 0.96,
  },
  header: {
    background: '#0D4D5E',
    logoHeightPx: 40,
    titleColor: '#FFFFFF',
    subtitleColor: '#AAD0D1',
    titleSizePx: 22,
    subtitleSizePx: 13,
    sticky: true,
  },
  footer: {
    background: '#0D4D5E',
    textColor: 'rgba(255,255,255,.62)',
    fontFamily: 'Roboto',
    fontSizePx: 10,
    uppercase: true,
  },
  cards: {
    background: '#FFFFFF',
    radiusPx: 10,
    shadow: '0 1px 4px rgba(13,77,94,.07)',
    defaultAccent: '#AAD0D1',
    strongAccent: '#0D4D5E',
    accentWidthPx: 4,
  },
  metrics: {
    accentPosition: 'top',
    accentWidthPx: 3,
    valueSizePx: 21,
  },
  tables: {
    headerTextColor: '#417483',
    bodyTextColor: '#0D4D5E',
    headerSizePx: 9,
    bodySizePx: 11,
    rowBorder: 'rgba(65,116,131,.08)',
    headerBorder: 'rgba(65,116,131,.20)',
  },
  controls: {
    radiusPx: 6,
    border: 'rgba(65,116,131,.20)',
    focusColor: '#417483',
    primaryBackground: '#0D4D5E',
    primaryHoverBackground: '#417483',
    secondaryBackground: '#FFFFFF',
    secondaryText: '#0D4D5E',
    transitionMs: 300,
  },
  navigation: {
    tabs: {
      visualStyle: 'analytics',
      containerBackground: '#417483',
      textColor: 'rgba(255,255,255,.60)',
      activeTextColor: '#FFFFFF',
      hoverTextColor: 'rgba(255,255,255,.85)',
      activeIndicator: 'bottom-border',
      activeIndicatorColor: '#FFFFFF',
      activeIndicatorWidthPx: 3,
      buttonBackground: 'transparent',
      buttonRadiusPx: 0,
      uppercase: true,
      fontSizePx: 11,
      fontWeight: 600,
      letterSpacingEm: 0.06,
      transitionMs: 200,
    },
  },
  responsive: {
    breakpointsPx: {
      mobileMax: 767,
      tabletMin: 768,
      desktopMin: 1024,
      wideMin: 1280,
    },
    page: {
      desktop: { paddingXRem: 1.8, paddingYRem: 1.3 },
      tablet: { paddingXRem: 1.25, paddingYRem: 1.1 },
      mobile: { paddingXRem: 1.0, paddingYRem: 0.9 },
    },
    header: {
      desktop: {
        logoHeightPx: 40,
        showTitle: true,
        showSubtitle: true,
        showStatus: true,
        compact: false,
      },
      tablet: {
        logoHeightPx: 36,
        showTitle: true,
        showSubtitle: true,
        showStatus: true,
        compact: true,
      },
      mobile: {
        logoHeightPx: 32,
        showTitle: true,
        showSubtitle: false,
        showStatus: false,
        compact: true,
      },
    },
    tabs: {
      desktop: {
        layout: 'horizontal',
        overflowX: 'visible',
        wrap: false,
        sticky: true,
        tabPaddingXRem: 1.2,
        tabPaddingYRem: 0.65,
      },
      tablet: {
        layout: 'horizontal-scroll',
        overflowX: 'auto',
        wrap: false,
        sticky: true,
        tabPaddingXRem: 0.95,
        tabPaddingYRem: 0.6,
      },
      mobile: {
        layout: 'horizontal-scroll',
        overflowX: 'auto',
        wrap: false,
        sticky: true,
        scrollSnap: true,
        tabPaddingXRem: 0.8,
        tabPaddingYRem: 0.55,
        useHamburger: false,
        stackTabs: false,
        renderAsButtons: false,
      },
    },
    cards: {
      desktopColumnsDefault: 3,
      tabletColumnsDefault: 2,
      mobileColumnsDefault: 1,
    },
    metrics: {
      desktopColumnsDefault: 4,
      tabletColumnsDefault: 2,
      mobileColumnsDefault: 1,
    },
    tables: {
      desktop: { behavior: 'full-table' },
      tablet: { behavior: 'horizontal-scroll' },
      mobile: {
        behavior: 'horizontal-scroll',
        collapseColumns: false,
        preserveDataColumns: true,
      },
    },
    footer: {
      desktop: { layout: 'row', align: 'space-between' },
      tablet: { layout: 'row', align: 'space-between' },
      mobile: { layout: 'stacked', align: 'start' },
    },
  },
  chartPalette: {
    product: {
      day: '#D4CEC6',
      weekArea: '#8B3A2F',
      weekDns: '#417483',
      seasonArea: '#7A7875',
      seasonDns: '#AAD0D1',
    },
    hierarchy: {
      primary: '#0D4D5E',
      secondary: '#417483',
      tertiary: '#AAD0D1',
    },
    yearSeries: ['#0D4D5E', '#5A8F9E', '#8AB8C4', '#C8E8E9'],
  },
  assets: {
    brandDirectory: 'brand',
    webLogoFile: 'logo-web.png',
    printLogoFile: 'logo.png',
  },
  print: {
    pageSize: 'A4',
    orientation: 'landscape',
    marginMm: 10,
    logoFile: 'logo.png',
    logoHeightMm: 14,
    titleSizePt: 15,
    subtitleSizePt: 9,
    bodySizePt: 8,
    tableHeaderSizePt: 7,
    tableBodySizePt: 7,
    rowMinHeightMm: 7,
    borderColor: '#B8C9CE',
    headerTextColor: '#0D4D5E',
    footerTextColor: '#5A7F8A',
    showGeneratedAt: true,
    hideInteractiveControls: true,
  },
  behavior: {
    bilingualPattern: 'de-it',
    denseDataUi: true,
    avoidDecorativeAiUi: true,
    interactionStyle: 'lightweight-brand-led',
  },
} as const;

export type DNSDesignSystem = typeof DNS_DESIGN_SYSTEM;
