export const DNS_SYSTEM_STATUS_VERSION = '0.4.0' as const;
export const DNS_SYSTEM_STATUS_VERIFIED_AT = '2026-10-01' as const;

export type DNSAdoptionState = 'adopted' | 'partial' | 'notYet' | 'na' | 'pending';

export const DNS_SYSTEM_STATUS_CRITERIA = [
  { id: 'designSystem', label: 'Design System' },
  { id: 'sharedData', label: 'Shared Data' },
  { id: 'firebase', label: 'Firebase' },
  { id: 'auth', label: 'Auth' },
  { id: 'sharedAssets', label: 'Shared Assets' },
  { id: 'regionLogos', label: 'Region Logos' },
  { id: 'motion', label: 'Motion' },
  { id: 'dataContracts', label: 'Data Contracts' },
  { id: 'accessibility', label: 'Accessibility' },
] as const;

export const DNS_SYSTEM_STATUS = [
  {
    id: 'shared-data',
    label: 'DNS Shared Data',
    repo: 'dolomitinordicski/dns-shared-data',
    phase: 'foundation-source',
    firebaseProject: 'dns-core',
    datasetVersion: 'Canonical v1.6 · Operational schema 4 · Design System v1.13.2 · Asset manifest v2',
    criteria: {
      designSystem: 'adopted',
      sharedData: 'adopted',
      firebase: 'adopted',
      auth: 'na',
      sharedAssets: 'adopted',
      regionLogos: 'adopted',
      motion: 'adopted',
      dataContracts: 'adopted',
      accessibility: 'adopted',
    },
    note: 'Canonical source for shared contracts, assets, design tokens and Firebase rules/seeds.',
  },
  {
    id: 'data-entry',
    label: 'DNS Data Entry',
    repo: 'dolomitinordicski/DNS-Data-Entry',
    phase: 'foundation-aligned',
    firebaseProject: 'dns-core',
    datasetVersion: 'Shared package pinned to Foundation / Design System v1.13.2',
    criteria: {
      designSystem: 'adopted',
      sharedData: 'adopted',
      firebase: 'adopted',
      auth: 'adopted',
      sharedAssets: 'adopted',
      regionLogos: 'adopted',
      motion: 'adopted',
      dataContracts: 'adopted',
      accessibility: 'adopted',
    },
    note: 'Reference operational consumer. Shared navigation runtime v1.13.2, stable first paint, regional and organization assets, module-level Data Contracts and Accessibility v1 are adopted. Orders, public shares, print and pricing overrides resolve organization logos centrally.',
  },
  {
    id: 'polls',
    label: 'DNS Polls',
    repo: 'dolomitinordicski/DNS-Polls-tool',
    phase: 'foundation-aligned',
    firebaseProject: 'separate Polls / PII domain',
    datasetVersion: 'Shared package pinned to Foundation / Design System v1.12.1',
    criteria: {
      designSystem: 'adopted',
      sharedData: 'partial',
      firebase: 'adopted',
      auth: 'adopted',
      sharedAssets: 'notYet',
      regionLogos: 'na',
      motion: 'adopted',
      dataContracts: 'na',
      accessibility: 'adopted',
    },
    note: 'Foundation shell v1.13.2 is adopted with shared navigation, motion, interaction and Accessibility v1. Privacy-sensitive poll data remains intentionally isolated in the separate Polls / PII domain; organization logos are N/A because Polls does not render canonical organizations.',
  },
  {
    id: 'flyer-studio',
    label: 'DNS Flyer Studio',
    repo: 'dolomitinordicski/DNS-Flyer-Studio',
    phase: 'in-migration',
    firebaseProject: 'app-specific Firebase configuration',
    datasetVersion: 'No shared package pin detected',
    criteria: {
      designSystem: 'notYet',
      sharedData: 'partial',
      firebase: 'partial',
      auth: 'pending',
      sharedAssets: 'partial',
      regionLogos: 'partial',
      motion: 'notYet',
      dataContracts: 'notYet',
      accessibility: 'notYet',
    },
    note: 'Active regional color-logo selections now point to DNS Shared Data, including the current Biathlon Antholz 2026/27 asset. Some legacy/local logo files and non-region brand assets remain, so full shared-asset adoption is still partial.',
  },
  {
    id: 'fair',
    label: 'DNS FAIR',
    repo: 'dolomitinordicski/fairmodel',
    phase: 'foundation-ui-aligned',
    firebaseProject: 'fair-modell · separate operational persistence',
    datasetVersion: 'Foundation / Design System v1.13.2 · FAIR contract foundation-defined',
    criteria: {
      designSystem: 'adopted',
      sharedData: 'adopted',
      firebase: 'partial',
      auth: 'pending',
      sharedAssets: 'adopted',
      regionLogos: 'adopted',
      motion: 'adopted',
      dataContracts: 'adopted',
      accessibility: 'adopted',
    },
    note: 'Foundation shell, canonical navigation, shared print runtime/tokens, shared web logo, canonical regional/organization-logo manifest, motion/interaction and Accessibility v1 are adopted. Organization breakdown and print resolve canonical organization logos. FAIR uses Tailwind v4/Vite with legacy popup printing, local logo copies, Tailwind v3/PostCSS config and the vanilla-JS backup removed. FAIR calculation logic and existing fair-modell persistence remain unchanged; the FAIR Data Contract is still foundation-defined pending data-domain integration.',
  },
  {
    id: 'analytics',
    label: 'DNS Analytics',
    repo: 'dolomitinordicski/analytics',
    phase: 'foundation-ui-aligned',
    firebaseProject: 'dns-core master connection · operational analytics migration pending A.3',
    datasetVersion: 'Foundation / Design System v1.13.2 · A.2.1 compatibility dataset · Analytics measurement contract pending A.3',
    criteria: {
      designSystem: 'adopted',
      sharedData: 'adopted',
      firebase: 'partial',
      auth: 'pending',
      sharedAssets: 'adopted',
      regionLogos: 'adopted',
      motion: 'adopted',
      dataContracts: 'partial',
      accessibility: 'adopted',
    },
    note: 'A.2.1 complete: Vite/React/TypeScript/Tailwind v4, canonical navigation, Accessibility, shared print runtime, DNS brand/region assets and DNS_Core master-data connection are adopted. The original Analytics modules plus Network Reliability, Advanced Analytics, Übernachtungen and Langlauf-Intensität are consolidated. A.3 will replace the preserved compatibility datasets with canonical operational sources and finalize the Analytics measurement contract.',
  },
  {
    id: 'faktura',
    label: 'DNS Faktura / Commercial',
    repo: null,
    phase: 'foundation-defined',
    firebaseProject: 'DNS Commercial target',
    datasetVersion: 'Billing Preparation v0.1 · accounting integration intentionally out of scope',
    criteria: {
      designSystem: 'notYet',
      sharedData: 'partial',
      firebase: 'notYet',
      auth: 'notYet',
      sharedAssets: 'notYet',
      regionLogos: 'na',
      motion: 'notYet',
      dataContracts: 'adopted',
      accessibility: 'notYet',
    },
    note: 'Faktura is defined as an internal billing-preparation tool only: it calculates billable amounts by organization/area and does not create official invoices, track payments or integrate accounting software.',
  },
  {
    id: 'partner-portal',
    label: 'Partner Portal',
    repo: null,
    phase: 'planned',
    firebaseProject: 'DNS Platform target',
    datasetVersion: 'Foundation access model defined',
    criteria: {
      designSystem: 'notYet',
      sharedData: 'notYet',
      firebase: 'notYet',
      auth: 'partial',
      sharedAssets: 'notYet',
      regionLogos: 'partial',
      motion: 'notYet',
      dataContracts: 'partial',
      accessibility: 'pending',
    },
    note: 'Portal role, memberships and access-grant model are defined at Foundation level; application adoption remains pending.',
  },
] as const;

export type DNSSystemStatusEntry = (typeof DNS_SYSTEM_STATUS)[number];
